/**
 * Angebot (offer) store — persisted in PostgreSQL via Prisma.
 *
 * An Angebot is created by the admin from an amended Anfrage (submission).
 * One Anfrage can have many Angebote, but only one is active at a time.
 */

import { prisma } from "@/lib/db";
import type { ProjectPlan } from "@/lib/plan-template";

export interface Angebot {
  id: string;
  angebotNummer?: string;
  submissionId: string;
  version: number;
  status: "draft" | "sent" | "accepted" | "rejected_by_client";
  createdAt: string;
  sentAt?: string;

  // Admin-set pricing
  festpreis: number;
  aufwand: number; // Personentage

  // PDF (set after client accepts)
  pdfFileId?: string;

  // LLM-generated project plan
  plan: ProjectPlan;

  // Admin comments
  adminNotes?: string;

  // Customer rejection feedback
  clientFeedback?: string;

  // Auto-generated Angebot (SLA breach → auto-generation)
  isAutoGenerated?: boolean;
  autoGeneratedAt?: string;

  // Demand factor at time of Angebot creation
  demandFactor?: number;

  // Betreuung package (months) selected by customer at acceptance
  betreuungMonate?: number;
}

// ─── Helpers ──────────────────────────────────────────────────────

function dbToAngebot(r: Record<string, unknown>): Angebot {
  return {
    id: r.id as string,
    angebotNummer: (r.angebotNummer as string) || undefined,
    submissionId: r.submissionId as string,
    version: r.version as number,
    status: r.status as Angebot["status"],
    createdAt: (r.createdAt as Date).toISOString(),
    sentAt: r.sentAt ? (r.sentAt as Date).toISOString() : undefined,
    festpreis: r.festpreis as number,
    aufwand: r.aufwand as number,
    pdfFileId: (r.pdfFileId as string) || undefined,
    plan: r.plan as ProjectPlan,
    adminNotes: (r.adminNotes as string) || undefined,
    clientFeedback: (r.clientFeedback as string) || undefined,
    isAutoGenerated: (r.isAutoGenerated as boolean) || undefined,
    autoGeneratedAt: r.autoGeneratedAt ? (r.autoGeneratedAt as Date).toISOString() : undefined,
    demandFactor: (r.demandFactor as number) ?? undefined,
    betreuungMonate: (r.betreuungMonate as number) ?? undefined,
  };
}

// ─── CRUD ─────────────────────────────────────────────────────────

export async function addAngebot(angebot: Angebot): Promise<void> {
  const angebotNummer = angebot.angebotNummer || await generateAngebotNummer();
  await prisma.angebot.create({
    data: {
      id: angebot.id,
      angebotNummer,
      submissionId: angebot.submissionId,
      version: angebot.version,
      status: angebot.status,
      festpreis: angebot.festpreis,
      aufwand: angebot.aufwand,
      plan: JSON.parse(JSON.stringify(angebot.plan)),
      pdfFileId: angebot.pdfFileId ?? null,
      adminNotes: angebot.adminNotes ?? null,
      clientFeedback: angebot.clientFeedback ?? null,
      isAutoGenerated: angebot.isAutoGenerated ?? false,
      autoGeneratedAt: angebot.autoGeneratedAt ? new Date(angebot.autoGeneratedAt) : null,
      demandFactor: angebot.demandFactor ?? null,
      sentAt: angebot.sentAt ? new Date(angebot.sentAt) : null,
    },
  });
}

export async function getAngebotById(id: string): Promise<Angebot | undefined> {
  const r = await prisma.angebot.findUnique({ where: { id } });
  if (!r) return undefined;
  return dbToAngebot(r as unknown as Record<string, unknown>);
}

export async function getAngeboteBySubmission(submissionId: string): Promise<Angebot[]> {
  const rows = await prisma.angebot.findMany({
    where: { submissionId },
    orderBy: { version: "desc" },
  });
  return rows.map((r) => dbToAngebot(r as unknown as Record<string, unknown>));
}

export async function getActiveAngebot(submissionId: string): Promise<Angebot | undefined> {
  const row = await prisma.angebot.findFirst({
    where: {
      submissionId,
      status: { in: ["sent", "draft"] },
    },
    orderBy: { version: "desc" },
  });
  if (!row) return undefined;
  return dbToAngebot(row as unknown as Record<string, unknown>);
}

/**
 * Generate a sequential Angebotsnummer in format AN-{YYYY}-{NNNN}.
 * Queries the database for the highest existing number in the current year.
 */
export async function generateAngebotNummer(): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `AN-${year}-`;

  const lastAngebot = await prisma.angebot.findFirst({
    where: {
      angebotNummer: { startsWith: prefix },
    },
    orderBy: { angebotNummer: "desc" },
    select: { angebotNummer: true },
  });

  let nextNumber = 1;
  if (lastAngebot?.angebotNummer) {
    const lastNum = parseInt(lastAngebot.angebotNummer.replace(prefix, ""), 10);
    if (!isNaN(lastNum)) {
      nextNumber = lastNum + 1;
    }
  }

  return `${prefix}${String(nextNumber).padStart(4, "0")}`;
}

/**
 * Generate a gap-free sequential Rechnungsnummer in format RE-{YYYY}-{NNNN}.
 * Queries the database for the highest existing number in the current year.
 */
export async function generateRechnungNummer(): Promise<string> {
  const year = new Date().getFullYear();
  const prefix = `RE-${year}-`;

  // Find the highest existing rechnungNummer for the current year
  const lastPayment = await prisma.payment.findFirst({
    where: {
      rechnungNummer: { startsWith: prefix },
    },
    orderBy: { rechnungNummer: "desc" },
    select: { rechnungNummer: true },
  });

  let nextNumber = 1;
  if (lastPayment?.rechnungNummer) {
    const lastNum = parseInt(lastPayment.rechnungNummer.replace(prefix, ""), 10);
    if (!isNaN(lastNum)) {
      nextNumber = lastNum + 1;
    }
  }

  return `${prefix}${String(nextNumber).padStart(4, "0")}`;
}

export async function updateAngebotStatus(
  id: string,
  status: "sent" | "accepted" | "rejected_by_client",
  feedback?: string
): Promise<Angebot | undefined> {
  try {
    const r = await prisma.angebot.update({
      where: { id },
      data: {
        status,
        ...(status === "sent" ? { sentAt: new Date() } : {}),
        ...(feedback ? { clientFeedback: feedback } : {}),
      },
    });
    return dbToAngebot(r as unknown as Record<string, unknown>);
  } catch {
    return undefined;
  }
}
