/**
 * Admin notification system for critical business and technical events.
 *
 * Creates Incidents in the admin backoffice and optionally sends
 * WhatsApp/email notifications for high-severity events.
 */

import { createIncident } from "@/lib/job-queue";

type EventSeverity = "critical" | "warning" | "info";

interface NotificationEvent {
  severity: EventSeverity;
  title: string;
  message: string;
  source: string;
  referenceId?: string;
}

// ─── Business Events ─────────────────────────────────────────────

/** New submission received (positive) */
export async function notifyNewSubmission(data: {
  submissionId: string;
  name: string;
  projekttyp: string;
  naechsterSchritt: "call" | "angebot";
  range?: { untergrenze: number; obergrenze: number };
}) {
  const rangeStr = data.range
    ? `${data.range.untergrenze.toLocaleString("de-DE")}–${data.range.obergrenze.toLocaleString("de-DE")} €`
    : "wird berechnet";

  await notify({
    severity: "info",
    title: `Neue Anfrage: ${data.name}`,
    message: `Projekttyp: ${data.projekttyp}\nPfad: ${data.naechsterSchritt === "call" ? "Call" : "Direktes Angebot"}\nPreisrahmen: ${rangeStr}\n\nSubmission: ${data.submissionId}`,
    source: "onboarding",
    referenceId: data.submissionId,
  });
}

/** Angebot accepted by client (positive) */
export async function notifyAngebotAccepted(data: {
  angebotId: string;
  submissionId: string;
  kundenName: string;
  festpreis: number;
}) {
  await notify({
    severity: "info",
    title: `Angebot angenommen: ${data.kundenName}`,
    message: `${data.kundenName} hat das Angebot über ${data.festpreis.toLocaleString("de-DE")} € angenommen.\n\nAngebot: ${data.angebotId}\nSubmission: ${data.submissionId}`,
    source: "angebot",
    referenceId: data.angebotId,
  });
}

/** Angebot rejected by client (negative) */
export async function notifyAngebotRejected(data: {
  angebotId: string;
  submissionId: string;
  kundenName: string;
  feedback?: string;
}) {
  await notify({
    severity: "warning",
    title: `Angebot abgelehnt: ${data.kundenName}`,
    message: `${data.kundenName} hat das Angebot abgelehnt.\n\n${data.feedback ? `Feedback: ${data.feedback}\n\n` : ""}Angebot: ${data.angebotId}\nSubmission: ${data.submissionId}`,
    source: "angebot",
    referenceId: data.angebotId,
  });
}

/** SLA breached — admin must act */
export async function notifySlaBreached(data: {
  submissionId: string;
  name: string;
  slaMinutes: number;
  autoGenerated: boolean;
}) {
  const status = data.autoGenerated
    ? "Auto-Angebot wurde generiert"
    : "Manuelle Bearbeitung erforderlich";

  await notify({
    severity: data.autoGenerated ? "warning" : "critical",
    title: `SLA-Verletzung: ${data.name}`,
    message: `Die SLA-Frist von ${data.slaMinutes} Minuten wurde überschritten.\n\nStatus: ${status}\nSubmission: ${data.submissionId}`,
    source: "sla_check",
    referenceId: data.submissionId,
  });
}

/** Payment received (positive) */
export async function notifyPaymentReceived(data: {
  angebotId: string;
  kundenName: string;
  amount: number;
  type: string;
}) {
  await notify({
    severity: "info",
    title: `Zahlung eingegangen: ${data.kundenName}`,
    message: `${data.kundenName} hat ${(data.amount / 100).toLocaleString("de-DE")} € bezahlt (${data.type}).\n\nAngebot: ${data.angebotId}`,
    source: "payment",
    referenceId: data.angebotId,
  });
}

/** Payment failed (negative) */
export async function notifyPaymentFailed(data: {
  angebotId: string;
  kundenName: string;
  error: string;
}) {
  await notify({
    severity: "critical",
    title: `Zahlung fehlgeschlagen: ${data.kundenName}`,
    message: `Die Zahlung für ${data.kundenName} ist fehlgeschlagen.\n\nFehler: ${data.error}\nAngebot: ${data.angebotId}`,
    source: "payment",
    referenceId: data.angebotId,
  });
}

// ─── Technical Events ─────────────────────────────────────────────

/** System component unhealthy */
export async function notifySystemUnhealthy(data: {
  component: string;
  error: string;
}) {
  await notify({
    severity: "critical",
    title: `System-Ausfall: ${data.component}`,
    message: `Die Komponente "${data.component}" ist nicht erreichbar.\n\nFehler: ${data.error}`,
    source: "system",
  });
}

/** Email delivery failure */
export async function notifyEmailFailure(data: {
  to: string;
  subject: string;
  error: string;
  submissionId?: string;
}) {
  await notify({
    severity: "warning",
    title: `E-Mail-Zustellung fehlgeschlagen`,
    message: `E-Mail an ${data.to} konnte nicht gesendet werden.\n\nBetreff: ${data.subject}\nFehler: ${data.error}`,
    source: "email",
    referenceId: data.submissionId,
  });
}

/** WhatsApp delivery failure */
export async function notifyWhatsAppFailure(data: {
  phone: string;
  error: string;
  submissionId?: string;
}) {
  await notify({
    severity: "warning",
    title: `WhatsApp-Nachricht fehlgeschlagen`,
    message: `WhatsApp an ${data.phone} konnte nicht gesendet werden.\n\nFehler: ${data.error}`,
    source: "whatsapp",
    referenceId: data.submissionId,
  });
}

// ─── Core dispatch ────────────────────────────────────────────────

async function notify(event: NotificationEvent): Promise<void> {
  try {
    await createIncident({
      severity: event.severity,
      title: event.title,
      message: event.message,
      source: event.source,
      referenceId: event.referenceId,
    });

    // For critical events, also attempt WhatsApp notification to admin
    if (event.severity === "critical") {
      try {
        const { isInternalNotificationEnabled, getProvider } = await import("@/lib/whatsapp");
        if (isInternalNotificationEnabled()) {
          const provider = getProvider();
          const adminPhone = process.env.WHATSAPP_ADMIN_PHONE;
          if (provider && adminPhone) {
            await provider.sendTemplate(adminPhone, {
              templateName: "system_alert",
              language: "de",
              variables: [event.title, event.message.slice(0, 200)],
            });
          }
        }
      } catch {
        // WhatsApp notification best-effort
      }
    }
  } catch (err) {
    console.error("[Notification] Failed to create incident:", err);
  }
}
