import { NextResponse } from "next/server";
import {
  getDueSlaSubmissions,
  updateSubmissionStatus,
} from "@/lib/submissions";
import { generateAutoAngebot } from "@/lib/auto-angebot";
import { createIncident } from "@/lib/job-queue";
import { notifySlaBreached } from "@/lib/notifications";

export const dynamic = "force-dynamic";

/**
 * GET /api/cron/sla-check — Proactive SLA enforcement.
 * Internal endpoint — called every 5 min by the background scheduler.
 *
 * Finds submissions where slaDeadline is within the next 5 minutes
 * and generates the auto-Angebot BEFORE the deadline expires.
 *
 * Flow:
 *   1. Find sla_active submissions approaching deadline
 *   2. Skip "call" path (no auto-Angebot)
 *   3. Generate auto-Angebot proactively → "angebot_sent"
 *   4. If generation fails → mark "sla_breached" + create incident
 */
export async function GET() {
  const due = await getDueSlaSubmissions();

  if (due.length === 0) {
    return NextResponse.json({ checked: true, due: 0 });
  }

  const now = Date.now();
  const results: { id: string; status: string; reason?: string }[] = [];

  for (const submission of due) {
    const deadlineMs = submission.slaDeadline
      ? new Date(submission.slaDeadline).getTime()
      : 0;
    const isAlreadyBreached = deadlineMs <= now;

    // Call path — no auto-Angebot, just mark breached if past deadline
    if (submission.naechsterSchritt === "call") {
      if (isAlreadyBreached) {
        await updateSubmissionStatus(submission.id, "sla_breached");
        results.push({
          id: submission.id,
          status: "sla_breached",
          reason: "Call path — no auto-Angebot",
        });
      }
      continue;
    }

    // Generate auto-Angebot proactively (before or at deadline)
    const result = await generateAutoAngebot(submission);

    if (result.success) {
      results.push({
        id: submission.id,
        status: "angebot_sent",
        reason: `Auto-Angebot ${result.angebotId} generated${isAlreadyBreached ? "" : " (proaktiv vor Ablauf)"}`,
      });

      await notifySlaBreached({
        submissionId: submission.id,
        name: submission.name,
        slaMinutes: submission.slaMinutes ?? 0,
        autoGenerated: true,
      });

      console.log(
        `[SLA] Auto-Angebot ${result.angebotId} for ${submission.id}${isAlreadyBreached ? " (nach Ablauf)" : " (vor Ablauf)"}`
      );
    } else {
      // Generation failed — mark as breached + incident
      await updateSubmissionStatus(submission.id, "sla_breached");

      results.push({
        id: submission.id,
        status: "sla_breached",
        reason: result.reason || "Auto-generation failed",
      });

      await createIncident({
        severity: "critical",
        title: "SLA: Auto-Angebot fehlgeschlagen",
        message: `Submission ${submission.id} (${submission.name}):\n${result.reason || "Unbekannt"}\n\nManuelle Bearbeitung erforderlich.`,
        source: "sla_check",
        referenceId: submission.id,
      });

      console.error(
        `[SLA] Auto-Angebot failed for ${submission.id}: ${result.reason}`
      );
    }
  }

  console.log(`[SLA] Processed ${due.length} due submissions`, results);

  return NextResponse.json({
    checked: true,
    due: due.length,
    results,
  });
}
