import { NextResponse } from "next/server";
import { getSubmissionById, updateSubmissionStatus } from "@/lib/submissions";
import { getAngebotById, updateAngebotStatus } from "@/lib/angebote";
import { generateAngebotPdf } from "@/lib/pdf/generate";
import { uploadFile } from "@/lib/seaweedfs";
import { sendAngebotConfirmationEmail } from "@/lib/email";
import { bootstrapProject } from "@/lib/project-bootstrap";

interface RouteParams {
  params: Promise<{ id: string }>;
}

// GET /api/angebot/[id] — Customer-facing: get Angebot data
export async function GET(_request: Request, { params }: RouteParams) {
  const { id } = await params;
  const angebot = await getAngebotById(id);

  if (!angebot) {
    return NextResponse.json({ error: "Nicht gefunden" }, { status: 404 });
  }

  // Get linked submission for project details
  const submission = await getSubmissionById(angebot.submissionId);
  if (!submission) {
    return NextResponse.json({ error: "Anfrage nicht gefunden" }, { status: 404 });
  }

  // Return data safe for the customer
  const response: Record<string, unknown> = {
    id: angebot.id,
    status: angebot.status,
    version: angebot.version,
    createdAt: angebot.createdAt,
    isAutoGenerated: angebot.isAutoGenerated,
    // Submission data
    name: submission.name,
    projekttyp: submission.projekttyp,
    beschreibung: submission.beschreibung,
    funktionen: submission.funktionen,
    designLevel: submission.designLevel,
    zeitrahmenMvp: submission.zeitrahmenMvp,
    zeitrahmenFinal: submission.zeitrahmenFinal,
    betriebUndWartung: submission.betriebUndWartung,
  };

  // Only show pricing + plan if Angebot is sent, accepted, or rejected_by_client
  if (["sent", "accepted", "rejected_by_client"].includes(angebot.status)) {
    response.festpreis = angebot.festpreis;
    response.aufwand = angebot.aufwand;
    response.plan = angebot.plan;
  }

  return NextResponse.json(response);
}

// PATCH /api/angebot/[id] — Customer accepts or rejects the Angebot
export async function PATCH(request: Request, { params }: RouteParams) {
  const { id } = await params;
  const body = await request.json();
  const { action, feedback } = body as {
    action: "accept" | "reject";
    feedback?: string;
  };

  if (!action || !["accept", "reject"].includes(action)) {
    return NextResponse.json(
      { error: "Ungültige Aktion" },
      { status: 400 }
    );
  }

  const angebot = await getAngebotById(id);
  if (!angebot) {
    return NextResponse.json({ error: "Nicht gefunden" }, { status: 404 });
  }

  // Only sent Angebote can be accepted/rejected by customer
  if (angebot.status !== "sent") {
    return NextResponse.json(
      { error: "Angebot ist nicht verfügbar" },
      { status: 400 }
    );
  }

  if (action === "accept") {
    await updateAngebotStatus(id, "accepted");
    await updateSubmissionStatus(angebot.submissionId, "accepted");

    // Get submission for PDF data + project bootstrap
    const submission = await getSubmissionById(angebot.submissionId);

    // Generate PDF + store + send email + bootstrap project (fire-and-forget)
    (async () => {
      try {
        if (!submission) {
          console.error("[Accept] Submission not found for PDF generation");
          return;
        }

        // Generate PDF
        const pdfBuffer = await generateAngebotPdf({
          angebotId: angebot.id,
          kundenName: submission.name,
          firma: submission.firma,
          email: submission.email,
          festpreis: angebot.festpreis,
          aufwand: angebot.aufwand,
          projektBeschreibung: submission.beschreibung,
          plan: angebot.plan,
          createdAt: angebot.createdAt,
        });
        console.log(`[Accept] PDF generated: ${pdfBuffer.length} bytes`);

        // Store in SeaweedFS
        try {
          const fid = await uploadFile(pdfBuffer, `Angebot-${angebot.id}.pdf`);
          angebot.pdfFileId = fid;
          console.log(`[Accept] PDF stored in SeaweedFS: fid=${fid}`);
        } catch (storageError) {
          console.error("[Accept] SeaweedFS upload failed (PDF still sent via email):", storageError);
        }

        // Send confirmation email with PDF attachment
        try {
          await sendAngebotConfirmationEmail({
            to: submission.email,
            kundenName: submission.name,
            festpreis: angebot.festpreis,
            pdfBuffer,
            angebotId: angebot.id,
          });
        } catch (emailError) {
          console.error("[Accept] Confirmation email failed:", emailError);
        }

        // Project Bootstrap — generate project structure
        try {
          const bootstrap = bootstrapProject(submission, angebot);
          if (bootstrap.success) {
            await updateSubmissionStatus(submission.id, "project_bootstrapped");
            console.log(
              `[Accept] Project bootstrapped: ${bootstrap.projectName} (${bootstrap.files.length} files)`
            );
          } else {
            console.error("[Accept] Bootstrap failed:", bootstrap.error);
          }
        } catch (bootstrapError) {
          console.error("[Accept] Bootstrap error:", bootstrapError);
        }
      } catch (pdfError) {
        console.error("[Accept] PDF generation failed:", pdfError);
      }
    })();
  } else {
    await updateAngebotStatus(id, "rejected_by_client", feedback);
    await updateSubmissionStatus(angebot.submissionId, "rejected_by_client", feedback);
  }

  return NextResponse.json({
    success: true,
    status: action === "accept" ? "accepted" : "rejected_by_client",
  });
}
