import { NextResponse } from "next/server";
import { getSubmissionById, updateSubmissionStatus } from "@/lib/submissions";
import { getAngebotById, updateAngebotStatus } from "@/lib/angebote";
import { bootstrapProject } from "@/lib/project-bootstrap";
import { enqueueJob, processJobs } from "@/lib/job-queue";
export const dynamic = "force-dynamic";

interface RouteParams {
  params: Promise<{ id: string }>;
}

// GET /api/angebot/[id] — Customer-facing: get Angebot data
export async function GET(_request: Request, { params }: RouteParams) {
  const { id } = await params;
  const angebot = await getAngebotById(id);

  if (!angebot) {
    return NextResponse.json({ error: "Nicht gefunden" }, { status: 404 });
  }

  // Get linked submission for project details
  const submission = await getSubmissionById(angebot.submissionId);
  if (!submission) {
    return NextResponse.json({ error: "Anfrage nicht gefunden" }, { status: 404 });
  }

  // Return data safe for the customer
  const response: Record<string, unknown> = {
    id: angebot.id,
    status: angebot.status,
    version: angebot.version,
    createdAt: angebot.createdAt,
    isAutoGenerated: angebot.isAutoGenerated,
    // Submission data
    name: submission.name,
    projekttyp: submission.projekttyp,
    beschreibung: submission.beschreibung,
    funktionen: submission.funktionen,
    designLevel: submission.designLevel,
    zeitrahmenMvp: submission.zeitrahmenMvp,
    zeitrahmenFinal: submission.zeitrahmenFinal,
    betriebUndWartung: submission.betriebUndWartung,
  };

  // Only show pricing + plan if Angebot is sent, accepted, or rejected_by_client
  if (["sent", "accepted", "rejected_by_client"].includes(angebot.status)) {
    response.festpreis = angebot.festpreis;
    response.aufwand = angebot.aufwand;
    response.plan = angebot.plan;
  }

  return NextResponse.json(response);
}

// PATCH /api/angebot/[id] — Customer accepts or rejects the Angebot
export async function PATCH(request: Request, { params }: RouteParams) {
  const { id } = await params;
  const body = await request.json();
  const { action, feedback } = body as {
    action: "accept" | "reject";
    feedback?: string;
  };

  if (!action || !["accept", "reject"].includes(action)) {
    return NextResponse.json(
      { error: "Ungültige Aktion" },
      { status: 400 }
    );
  }

  const angebot = await getAngebotById(id);
  if (!angebot) {
    return NextResponse.json({ error: "Nicht gefunden" }, { status: 404 });
  }

  // Only sent Angebote can be accepted/rejected by customer
  if (angebot.status !== "sent") {
    return NextResponse.json(
      { error: "Angebot ist nicht verfügbar" },
      { status: 400 }
    );
  }

  if (action === "accept") {
    await updateAngebotStatus(id, "accepted");
    await updateSubmissionStatus(angebot.submissionId, "accepted");

    // Get submission for PDF data + project bootstrap
    const submission = await getSubmissionById(angebot.submissionId);

    // Enqueue PDF+Email as a reliable job (retries on failure, creates incident if exhausted)
    if (submission) {
      await enqueueJob(
        "angebot_accepted_email",
        {
          angebotId: angebot.id,
          to: submission.email,
          kundenName: submission.name,
          firma: submission.firma,
          email: submission.email,
          festpreis: angebot.festpreis,
          aufwand: angebot.aufwand,
          projektBeschreibung: submission.beschreibung,
          plan: angebot.plan,
          createdAt: angebot.createdAt,
        },
        5,
        `angebot_accepted_email:${angebot.id}`
      );

      // Try to process immediately (fire-and-forget — retry handled by cron if this fails)
      processJobs().catch((err) =>
        console.error("[Accept] Immediate job processing failed, cron will retry:", err)
      );

      // Project Bootstrap (fire-and-forget, separate from email)
      (async () => {
        try {
          const bootstrap = bootstrapProject(submission, angebot);
          if (bootstrap.success) {
            await updateSubmissionStatus(submission.id, "project_bootstrapped");
            console.log(
              `[Accept] Project bootstrapped: ${bootstrap.projectName} (${bootstrap.files.length} files)`
            );
          }
        } catch (err) {
          console.error("[Accept] Bootstrap error:", err);
        }
      })();
    }
  } else {
    await updateAngebotStatus(id, "rejected_by_client", feedback);
    await updateSubmissionStatus(angebot.submissionId, "rejected_by_client", feedback);
  }

  if (action === "accept") {
    // Return payment options with discount calculations
    const { calculatePaymentOptions, BANKVERBINDUNG } = await import("@/lib/constants");
    const options = calculatePaymentOptions(angebot.festpreis);
    return NextResponse.json({
      success: true,
      status: "accepted",
      payment: {
        festpreis: angebot.festpreis,
        options,
        bank: {
          ...BANKVERBINDUNG,
          verwendungszweck: `Angebot ${angebot.id}`,
        },
      },
    });
  }

  return NextResponse.json({
    success: true,
    status: "rejected_by_client",
  });
}
